[unstable]
codegen-backend = true
mtime-on-use = true
cargo-lints = true
gitoxide = true

[profile.dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
